simple-factory:
  shape: square


factory-method:
  factory: jpg


abstract-factory:
  factory: winMobile


builder:
  builder: member


adapter:
  adapter: db


bridge:
  converter: converter
  db: sqlServer
  ff: xml